let stockProductos = [
    {id: 1, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "L", img: '/img/remera.jpg', cantidad:1},
    {id: 2, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "XL", img: '/img/remera.jpg', cantidad:1},
    {id: 3, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 500, talle: "M", img: '/img/remera.jpg', cantidad:1},
    {id: 4, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "M", img: '/img/remera.jpg', cantidad:1},
    {id: 5, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: '/img/remera.jpg', cantidad:1},
    {id: 6, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: '/img/remera.jpg', cantidad:1},
    {id: 7, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "M", img: '/img/remera.jpg', cantidad:1},
    {id: 8, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: '/img/remera.jpg', cantidad:1},
    {id: 9, nombre: "Remera Urbana", tipo: "remera", desc: "Una remera que re va con vos", precio: 700, talle: "S", img: '/img/remera.jpg', cantidad:1},
    {id: 10, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 900, talle: "XL", img: '/img/camisa.jpg', cantidad:1},
    {id: 11, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 1400, talle: "L", img: '/img/camisa.jpg', cantidad:1},
    {id: 12, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 7000, talle: "M", img: '/img/camisa.jpg', cantidad:1},
    {id: 13, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 777, talle: "S", img: '/img/camisa.jpg', cantidad:1},
    {id: 14, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 234, talle: "M", img: '/img/camisa.jpg', cantidad:1},
    {id: 15, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 1600, talle: "L", img: '/img/camisa.jpg', cantidad:1},
    {id: 16, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 777, talle: "XL", img: '/img/camisa.jpg', cantidad:1},
    {id: 17, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 234, talle: "S", img: '/img/camisa.jpg', cantidad:1},
    {id: 18, nombre: "Camisa Urbana", tipo: "camisa", desc: "Una camisa que re va con vos", precio: 1600, talle: "S", img: '/img/camisa.jpg', cantidad:1},
    {id: 19, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 1600, talle: "XL", img: '/img/pantalon.jpg', cantidad:1},
    {id: 20, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 3200, talle: "L", img: '/img/pantalon.jpg', cantidad:1},
    {id: 21, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 2300, talle: "M", img: '/img/pantalon.jpg', cantidad:1},
    {id: 22, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 5600, talle: "XL", img: '/img/pantalon.jpg', cantidad:1},
    {id: 23, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 1700, talle: "S", img: '/img/pantalon.jpg', cantidad:1},
    {id: 24, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: '/img/pantalon.jpg', cantidad:1},
    {id: 25, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 5600, talle: "M", img: '/img/pantalon.jpg', cantidad:1},
    {id: 26, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 1700, talle: "XL", img: '/img/pantalon.jpg', cantidad:1},
    {id: 27, nombre: "Pantalon Urbano", tipo: "pantalon", desc: "Una pantalon que re va con vos", precio: 800, talle: "S", img: '/img/pantalon.jpg', cantidad:1},
]

